### ISSUE TITLE
Cannot connect to cluster

### ISSUE THREAD

**Issue by pgrm** [paralect/robomongo#828] opened 2015-03-30 11:00 UTC
I used to use Robomongo to connect to a MongoDB of a customer of mine, but since the set up a cluster it doesn't work anymore. However I can still connect normally to it via Mongo Management Studio and MongoChef.

Unfortunately I don't have any details about the cluster. When I tested the connection it said it can reach the server but the problem was in the authorization. However when I type in the same credentials in Mongo Management Studio as `user:password@server.dns:PORT` and selected the same databases to authenticate on (`data_db`) like I did in Robomongo it worked.

I know, I'm not providing a lot of information, but maybe you know how I could get some more info?

    {
     "connectionName" : "high availability cluster which doesn't work",
     "credentials" : [
      {
       "databaseName" : "data_db",
       "enabled" : true,
       "userName" : "user",
       "userPassword" : "password"
      }
     ],
     "defaultDatabase" : "",
     "serverHost" : "server.dns",
     "serverPort" : PORT,
     "sshAuthMethod" : 0,
     "sshHost" : "",
     "sshPassphrase" : "",
     "sshPort" : 22,
     "sshPrivateKey" : "",
     "sshPublicKey" : "",
     "sshUserName" : "",
     "sshUserPassword" : "",
     "sslEnabled" : false,
     "sslPemKeyFile" : ""
    }

**Comment by stennie** [comment] 2015-03-30 11:09
What version of MongoDB server is the cluster running? If the cluster has been upgraded to MongoDB 3.0.x with the newer SCRAM-SHA-1 auth, that isn't supported by Robomongo 0.8.x yet (it's being worked on for 0.9.0).

**Comment by pgrm** [comment] 2015-03-30 11:14
ok thx, that can be the problem. Unfortunately I don't have those information, but they upgraded it now over the weekend, and also told me now afterwards to use mongochef so probably they went for the latest version and new about this problem already

I'll try it than when 0.9 will come out, thx

**Comment by stennie** [comment] 2015-03-30 11:16
@pgrm Thanks .. will close as a dupe of #766 (which is the issue to work on authentication for 0.9.0 release).

**Closed by stennie** 2015-03-30 11:16 UTC
Labels: needs definition
