### ISSUE TITLE
Robomongo shell line is too small

### ISSUE THREAD

**Issue by JonathanPicques** [paralect/robomongo#847] opened 2015-04-16 19:23 UTC
Robomongo shell is too small I can't type commands in it, built from sources on Debian Jessie SID.
It seems each line is cut in half

![image](https://cloud.githubusercontent.com/assets/1839757/7189365/57944600-e476-11e4-9a83-1f86ff6acef9.png)

**Comment by stennie** [comment] 2015-04-21 11:05
@JonathanPicques Thanks for reporting .. this is actually a duplicate of #649. A partial workaround has been committed for Robomongo 0.8.6 (see #803) which will you to override the default fonts by editing your robomongo config file. Will be making test packages for 0.8.6 this weekend if you are able to help test (links will be added to the relevant placeholder tasks in the [0.8.6 milestone](https://github.com/paralect/robomongo/issues?utf8=%E2%9C%93&q=is%3Aopen+milestone%3A%22Robomongo+0.8.6%22+label%3Atask+create)).

**Closed by stennie** 2015-04-21 11:05 UTC
Labels: duplicate, os-linux

**Comment by JonathanPicques** [comment] 2015-04-21 12:11
@stennie Thanks, I'll sure test this weekend.

**Comment by dafur1900** [comment] 2016-06-28 16:58
Maybe you already solve this issue, but in case anybody else land here looking for hints, this change one work for me:

On your robomongo.json file ($HOME/./config/robomongo/robomongo.json), you probably have this variables set:  

"textFontFamily" : "", 
"textFontPointSize" : -1, 

I've changed to 
"textFontFamily" : "verdana",
 "textFontPointSize" : 10,

And presto, my robomongo worked as it should.
Tested wtih robomongo 0.9rcX.@ ubuntu like distro

**Comment by simsekgokhan** [comment] 2016-06-28 17:39
@dafur1900 thanks a lot for sharing. Hope it works for others as well.
