### ISSUE TITLE
Hope to see v0.9 recently

### ISSUE THREAD

**Issue by toboto** [paralect/robomongo#876] opened 2015-05-20 10:39 UTC
My server is 3.0.3,  Come on!

**Comment by parvanov** [comment] 2015-05-20 23:02
Really need support for Mongo 3.
Please just update the drivers even with no other changes.

**Comment by tarvitz** [comment] 2015-05-22 11:43
:+1:

**Comment by joshlopes** [comment] 2015-05-26 10:49
spaming does not help :)

**Comment by ChALkeR** [comment] 2015-06-08 20:44
Isn't this a dupe of #520?

**Comment by schetnikovich** [comment] 2016-01-27 17:06
[Robomongo 0.9.0 RC2](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/) supports MongoDB 3.x and WiredTiger engine.

**Closed by schetnikovich** 2016-01-27 17:06 UTC
Labels: duplicate
