### ISSUE TITLE
Ints converting to double and rounding

### ISSUE THREAD

**Issue by borigas** [paralect/robomongo#842] opened 2015-04-14 19:34 UTC
Robomongo is awesome. Thanks for all your hard work. I'm having a problem with rounding of ints though. I'm on version 0.8.5 on Windows 8
````
var myDoc = {MyInt : NumberInt(123456789)};
print(myDoc);

// Actual
/* 1 */
{
    "MyInt" : 1.23457e+008
}

// Expected
/* 1 */
{
    "MyInt" : 123456789
}
````

This is a minor inconvenience when just viewing the numbers. It becomes a more serious problem when editing a document. Because document's ints are rounded when opening the dialog, the rounded doubles get persisted when saving. This means clicking edit, making no changes, and clicking save will actually change both the type (int -> double) and data itself (rounded)

**Comment by stennie** [comment] 2015-04-15 06:25
@borigas Thanks for the bug report (and positive feedback). I believe this is a duplicate of #831, and is a bug introduced in Robomongo 0.8.5 with an updated QScintilla (editing component).

Looking into how to fix for 0.8.6.

**Closed by stennie** 2015-04-15 06:25 UTC
Labels: duplicate
