### ISSUE TITLE
Application quits unexpectedly when unplugging external monitor

### ISSUE THREAD

**Issue by yonatanzelnik** [paralect/robomongo#936] opened 2015-09-04 18:29 UTC

**Comment by simison** [comment] 2015-09-06 22:17
Duplicate of #829 

@yonatanzelnik Could you check your OSX version? I had the same issue but it disappeared after upgrading to OSX 10.10.5.

**Comment by yonatanzelnik** [comment] 2015-09-08 09:55
Got it. OSX is 10.10.3.

**Comment by anorsich** [comment] 2016-02-03 08:21
@yonatanzelnik I hope that this issue has been fixed with latest [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) release. Also I going to close this ticket as duplicate of #829, please use this ticket if it still does not work fo you or if you'll have any finding that will help us replicate the issue.

**Closed by anorsich** 2016-02-03 08:21 UTC
