### ISSUE TITLE
Crashes when you stop an operation

### ISSUE THREAD

**Issue by jjosephs** [paralect/robomongo#454] opened 2014-01-01 05:27 UTC
If I start a query or any command and press the red stop button before it finished and try to click the Robomongo screen again it crashes.

I'm using version 0.8.4 on windows 7.

It happens whether I use a local or remote instance of mongo.

**Comment by stennie** [comment] 2015-03-14 06:18
@jjosephs @pedronasser I can't reproduce this issue with a trivial test and there isn't enough information here to help.

It's possible this may have been fixed with subsequent updates to Robomongo and/or Qt.

It would be great if either of you are able to test with the [0.8.5 release packages](https://github.com/paralect/robomongo/issues?q=milestone%3A%22Robomongo+0.8.5%22+%22create+0.8.5%22+label%3Atask) to see if the problem still exists for you.

Please feel free to reopen with additional details of your environment and any steps to reproduce (i.e. the operation that is running when you click stop, # of tabs that are open, etc).

Thanks!

**Closed by stennie** 2015-03-14 06:18 UTC
Labels: needs repro
