### ISSUE TITLE
Editor Font Line too narrow

### ISSUE THREAD

**Issue by tuhlmann** [paralect/robomongo#478] opened 2014-02-22 09:02 UTC
Hi,

I'm using Robomongo on Ubuntu 13.10 with Infinality (http://www.infinality.net/) installed.
With Robomongo I notice that the space allocated per editor line is too narrow.

In a previous installation without Infinality (patches for Freetype for better font rendering) this did not happen, so I guess its somewhat related, please see screenshot for explanation.

Can you point me to a place in the source where I could modify the allocated space per editor line or maybe tell the widget the font size is larger than it actually is- or do you have another idea what the problem could be?

That's the first app I notice this problem, it doesn't seem to be a general thing...

Thanks,
Torsten.

![auswahl_003](https://f.cloud.github.com/assets/407319/2237322/67f67cf0-9b9f-11e3-8474-ea80a3ff0f8f.png)

**Comment by stennie** [comment] 2015-03-12 02:30
Closing as a duplicate of #478

**Closed by stennie** 2015-03-12 02:30 UTC
Labels: bug, os-linux
