### ISSUE TITLE
SSL/SSH support

### ISSUE THREAD

**Issue by mentallurg** [paralect/robomongo#951] opened 2015-09-28 00:30 UTC
Mongo Server 3.0.6 is set to accept SSL connections only. In Robomongo, enable checkbox "Use SSL protocol". When testing the conenction, Mongo server writes following in log:
    Failed to authenticate ...@... with mechanism MONGODB-CR: AuthenticationFailed MONGODB-CR credentials missing in the user document.

Expected behaviour: Robomongo establishes SSL connection and send user and password to the Mongo server.
Actual behaviour: Robomongo establishes an SSL connection (server log confirms that), but seems not to send credentials.

**Comment by anorsich** [comment] 2016-02-03 09:01
@mentallurg Thank you for submitting the issue. In latest release we had to disable ssl/ssh support. We will work to enable it soon. I am closing this issue as duplicate of #1002. You can use this ticket to keep tracking implementation progress.

**Closed by anorsich** 2016-02-03 09:01 UTC

**Comment by mentallurg** [comment] 2017-04-09 10:53
@anorsich: How can be something in the past a duplicate of something in the future? How can be ticket #951 created in 2015 a duplicate of #1002 created in 2016? You guys seem to have problems with common sense.

**Comment by IlyaDiallo** [comment] 2017-04-09 16:01
@mentallurg one possible reason for keeping newer issues instead of older is that comments are more interesting in the newer. Another possible reason is that there's already some commits attached to the newer. Another reason is mistakes (I'm sure you've heard about them). Also, if you love "common sense", it should tell you that when in doubt, it's better to be polite than to be rude ;-)
