### ISSUE TITLE
References are validated too strictly and perfectly fine references are considered invalid

### ISSUE THREAD

**Issue by josefsabl** [paralect/robomongo#968] opened 2015-11-05 09:44 UTC
The problem is with mappedsuperclasses and class discriminator field. See this picture: http://screenpresso.com/=xIOzg

This is considered invalid:

    "account" : {
        "$ref" : "Account",
        "$id" : ObjectId("55daf17feb4134b424000029"),
        "$db" : "mydb",
        "class" : "App\\Model\\Doc\\Account"
    },

To make it work, you have to change it to

    "account" : {
        "class" : "App\\Model\\Doc\\Account",
        "$ref" : "Account",
        "$id" : ObjectId("55daf17feb4134b424000029"),
        "$db" : "mydb"
    },

This workaround is however practically unusable and make Robomongo useless for us.

**Comment by anorsich** [comment] 2016-02-03 07:08
@josefsabl This is really frustrating issue. I am closing this one as duplicate of #912. Let's keep progress there.

**Closed by anorsich** 2016-02-03 07:08 UTC
