### ISSUE TITLE
RoboMongo closes when this collection is open

### ISSUE THREAD

**Issue by JCKodel** [paralect/robomongo#656] opened 2014-09-22 20:31 UTC
I have the following data on one of my collections:

	> db.AllTypes.find()
	{
		"_id" : "00jwts5k301ehgcljcqsh3b0ce",
		"CreationDate" : ISODate("2014-09-22T20:27:05.554Z"),
		"LastUpdate" : ISODate("2014-09-22T20:27:05.554Z"),
		"Boolean" : true,
		"Byte" : 255,
		"Short" : 32767,
		"Int" : 2147483647,
		"Long" : NumberLong("9223372036854775807"),
		"Float" : 1.7976931348623157e+308,
		"Double" : 1.7976931348623157e+308,
		"Decimal" : "79228162514264337593543950335",
		"DateTime" : ISODate("2014-09-22T20:27:05.502Z"),
		"String" : "String",
		"Guid" : BinData(3,"+Yap4G1jhk2OSq90YY9mkg=="),
		"NullableBoolean" : null,
		"NullableByte" : null,
		"NullableShort" : null,
		"NullableInt" : null,
		"NullableLong" : null,
		"NullableFloat" : null,
		"NullableDouble" : null,
		"NullableDecimal" : null,
		"NullableDateTime" : null,
		"NullableString" : null,
		"NullableGuid" : null
	}

While trying to open this colleciton in RoboMongo (0.84):

Faulting application name: Robomongo.exe, version: 0.8.4.0, time stamp: 0x52861314
Faulting module name: MSVCR110.dll, version: 11.0.51106.1, time stamp: 0x5098858e
Exception code: 0xc0000005
Fault offset: 0x0000df22
Faulting process id: 0x3058
Faulting application start time: 0x01cfd6a34a64360f
Faulting application path: C:\Program Files (x86)\Robomongo\Robomongo.exe
Faulting module path: C:\Program Files (x86)\Robomongo\MSVCR110.dll
Report Id: 08dc3e5e-4297-11e4-829d-ebad1fa7f8ee
Faulting package full name: 
Faulting package-relative application ID:

**Comment by stennie** [comment] 2015-03-19 10:39
Possibly a dupe of #748

**Closed** 2015-04-21 10:48 UTC
Labels: bug, duplicate
