### ISSUE TITLE
Copy collection on Mac

### ISSUE THREAD

**Issue by manuel-reil** [paralect/robomongo#924] opened 2015-07-29 11:09 UTC
Hi, 

I am missing the copy collection feature on OS X Yosemite 10.10.4. Robomongo 0.8.5 downloaded today.

Or do I just know where to click?

Thank you,
Manuel
![robomongo_copy_collection](https://cloud.githubusercontent.com/assets/10340109/8956104/f11623c0-35f2-11e5-9ffe-19fb9a3ae582.png)

**Comment by anorsich** [comment] 2016-02-03 07:45
@manuel-reil  Thank you for reporting this issue. Copy collection functionality does not stable at the moment. I am closing this issue as duplicate of #398. Please use it for reference to track implementation progress.

**Closed by anorsich** 2016-02-03 07:45 UTC
