### ISSUE TITLE
Connection to mongolabs fails with new version

### ISSUE THREAD

**Issue by hoegertn** [paralect/robomongo#824] opened 2015-03-27 08:22 UTC
I just switched to the latest version of Robomongo and now connections to mongolabs sandbox do not work anymore. The log at the bottom says connecting but nothing happens. Switching back to the old version works.

**Comment by stennie** [comment] 2015-03-27 08:31
@hoegertn Assuming you are referring to Robomongo 0.8.5 vs 0.8.4 (and not an earlier version) there shouldn't be any difference in the connection code.

Can you provide some more information on how you connect (eg. with auth, ssl, ssh), the remote MongoDB server version, and your O/S?

Thanks!

**Comment by hoegertn** [comment] 2015-03-27 08:35
Sorry for missing info.

Version 0.8.5 vs. 0.8.4

OS: Mac OS 10.10
Remote Server: https://mongolab.com/  Sandbox server
No SSL, no SSH, auth with user,pwd,authDB

**Comment by stennie** [comment] 2015-03-27 08:54
@hoegertn I just successfully tested Robomongo 0.8.5 and 0.8.4 (OS X 10.10.2) against a Mongolab sandbox (new deployment, mongodb 2.6.8). I created the config in Robomongo 0.8.5, and then restarted with Robomongo 0.8.4 and the identical config.

I set up connection details as per the info in mongolab:
 * Connection
   - address: ds#####.mongolab.com
   - port: ##### (custom port)

 * Authentication
   - perform authentication: (checked)
   - Database: (database name)
   - User Name + Password: (as per the database user I created)

 * Advanced
   - default database: (none)

Do you perhaps have a different default database set, or other connection detail which might explain the behaviour change?

Also, is this the first connection you open when starting Robomongo? If not, could you try restarting Robomongo and see if that makes a difference?

Thanks!

**Comment by yonib05** [comment] 2015-08-04 19:52
I'm having the same issue any updates on this?

**Comment by legatoo** [comment] 2015-08-21 01:53
same problem. sucking at connecting.

**Comment by alexhenker** [comment] 2015-08-24 09:32
Same problem, up!

**Comment by eggytronixx** [comment] 2015-08-28 21:51
i can't connect. Any luck?

**Comment by ekussberg** [comment] 2015-08-30 10:25
+1

**Comment by monisamjad** [comment] 2015-09-01 18:35
same issue. any luck?

**Comment by legatoo** [comment] 2015-09-02 01:43
Restart fix.

**Comment by jandujar** [comment] 2015-10-01 08:57
same issue, I think that the problem is that they just migrated to mongodb 3.0.6 and robomongo doesn't work with that version

**Comment by akaashanky** [comment] 2015-10-01 10:24
Same. I'm able to connect from the command line mongo client, but when I test the connection from Robomongo authorisation fails. This was working earlier, so I've a feeling this has something to do with Mongolab's upgrade a few hours earlier to MongoDB 3.

**Comment by satanin** [comment] 2015-10-01 14:17
Just the same as @akaashanky.

**Comment by mjlescano** [comment] 2015-10-01 22:38
Same here @akaashanky

**Comment by dlbrown06** [comment] 2015-10-02 09:42
Same issue...

**Comment by cybercussion** [comment] 2015-10-03 19:35
I tested mongo admin -u USER -p and filled it in and it worked.  Confirmed app not working which I'm glad you guys logged it or I'd have less hair right now.

**Comment by iancrowther** [comment] 2015-10-05 14:33
same issue!

**Comment by wutalman** [comment] 2015-10-05 14:36
+1

**Comment by juanmanavarro** [comment] 2015-10-06 07:39
+1

**Comment by yusufbadurohman** [comment] 2015-10-06 08:11
+1

**Comment by awe-some** [comment] 2015-10-06 12:13
Same issue!

**Comment by hems** [comment] 2015-10-06 15:15
+1

**Comment by adavkay** [comment] 2015-10-07 02:41
+1

**Comment by ant-fx** [comment] 2015-10-07 16:21
+1

**Comment by mozky** [comment] 2015-10-08 00:30
+1

**Comment by Pablodotnet** [comment] 2015-10-08 00:32
+1

**Comment by mlubovac** [comment] 2015-10-08 02:06
+1

**Comment by CodeZombieCH** [comment] 2015-10-08 09:31
+1

**Comment by whwnow** [comment] 2015-10-08 10:01
same as @akaashanky

**Comment by 26medias** [comment] 2015-10-08 15:55
+1

**Comment by ByTE1974** [comment] 2015-10-09 09:14
Same issue: "Test connection" button resulting in `Authorization failed` message.

**Comment by juanpabloaj** [comment] 2015-10-09 23:45
+1

**Comment by aheissenberger** [comment] 2015-10-10 08:10
:+1:

**Comment by halben** [comment] 2015-10-11 01:12
+1

**Comment by martynasb** [comment] 2015-10-11 15:30
+1

**Comment by Daylon** [comment] 2015-10-11 18:41
+1

**Comment by 78lab** [comment] 2015-10-12 04:52
+1

**Comment by HlodowigRaginwald** [comment] 2015-10-12 14:11
+1

**Comment by nickdk** [comment] 2015-10-12 14:31
+1

**Comment by nicefella** [comment] 2015-10-13 10:36
+1

**Comment by brianboyko** [comment] 2015-10-13 18:14
Same issue +1

**Comment by akaashanky** [comment] 2015-10-16 09:18
Looks to be a driver issue. The minimum compatible C++ driver for the version of MongoDB used by MongoLab is 1.0.0 according to the Mongo 3.0 release notes: http://docs.mongodb.org/manual/release-notes/3.0-compatibility/#driver-compatibility-changes

**Comment by AjmalSaid** [comment] 2015-10-16 13:24
+1

**Comment by hudsondaf** [comment] 2015-10-16 17:54
+1

**Comment by manuel140** [comment] 2015-10-16 19:30
+1

**Comment by rahulswarnkar** [comment] 2015-10-18 21:01
+1

**Comment by emaddoma** [comment] 2015-10-19 16:20
+1

**Comment by radko93** [comment] 2015-10-21 00:41
+1

**Comment by shahan312** [comment] 2015-10-21 00:49
+1

**Comment by bushev** [comment] 2015-10-21 13:49
+1

**Comment by budkin76** [comment] 2015-10-21 19:16
+1

**Comment by johan--** [comment] 2015-10-23 08:48
+1

**Comment by malcommac** [comment] 2015-10-23 18:13
+1

**Comment by dobre-robert-marius** [comment] 2015-10-23 20:37
+1

**Comment by luiseduardobrito** [comment] 2015-10-25 04:43
+1

**Comment by vbuhl** [comment] 2015-10-25 20:11
+1

**Comment by TravelingTechGuy** [comment] 2015-10-26 04:29
+1, RoboMongo 0.85, Windows 10: "Test connection" button resulting in Authorization failed message.
Same parameters work from Mongo client

**Comment by SBejga** [comment] 2015-10-26 11:31
+1

**Comment by andrewoodleyjr** [comment] 2015-10-27 05:40
+1

**Comment by alaouy** [comment] 2015-10-27 09:25
+1

**Comment by DuriDuri** [comment] 2015-10-27 17:55
+1

**Comment by JonForest** [comment] 2015-10-28 01:11
Would be great to know if this really is still 'waiting repro' which it seems lots of people have done, or if it is on the list to be fixed.  Do I need to find another tool?

**Comment by uneco** [comment] 2015-10-29 03:04
+1

**Comment by o-r-r** [comment] 2015-10-29 15:57
+1

**Comment by JulGor** [comment] 2015-10-29 16:40
+1

**Comment by andersonpimentel** [comment] 2015-10-29 17:11
@JonForest I'm switching to [MongoChef](http://3t.io/mongochef/). It's free for personal or non-commercial use.

I like RoboMongo a lot, but it's 7 months since this bug was opened.

**Comment by TravelingTechGuy** [comment] 2015-10-29 18:40
While their web site says "Note: We are working on an update with MongoDB 3.0 compatibility for the upcoming Robomongo 0.9.x release series.", the last time someone touched the source code was 7 months ago. It seems like either we need to fork-n-fix, or (very sadly) declare RoboMongo abandonware and move on. Can anyone on the original team comment?

**Comment by budkin76** [comment] 2015-10-29 18:55
Thanks for the suggestion for MongoChef @andersonpimentel! It's absolutely crazy this bug still exists. Oh well, it's their loss as we move on to other, better tools.

**Comment by ide8** [comment] 2015-10-30 13:57
+1

**Comment by franciscop** [comment] 2015-10-31 15:45
+1, same issue

**Comment by thibalte** [comment] 2015-11-04 12:34
+1

**Comment by sorousht** [comment] 2015-11-09 12:40
+1

**Comment by seefeld** [comment] 2015-11-10 21:04
+1

**Comment by timwells** [comment] 2015-11-13 13:49
+1

**Comment by ccheatham** [comment] 2015-11-14 19:31
+1

**Comment by mandarinamdar** [comment] 2015-11-15 10:24
+1

**Comment by mscherer82** [comment] 2015-11-15 13:49
+1

**Comment by Olmer1st** [comment] 2015-11-15 13:51
+1

**Comment by alex-alex2006hw** [comment] 2015-11-16 14:00
+1

**Comment by bartekcajdler** [comment] 2015-11-16 21:42
+1

**Comment by constantx** [comment] 2015-11-19 17:29
+1

**Comment by davidebettio** [comment] 2015-11-20 11:26
+1

**Comment by fivepapertigers** [comment] 2015-11-23 15:20
+1 downloading MongoChef now, but I miss my RoboMongo

**Comment by hastoukopsaro** [comment] 2015-11-24 20:33
+1

**Comment by weblancaster** [comment] 2015-11-24 21:02
just fyi. Commenting +1 won't help.

**Comment by Olmer1st** [comment] 2015-11-25 08:45
Ok. Moved to MongoChef.

**Comment by DeveloperAlex** [comment] 2015-12-05 01:46
I'm having the same issue - can't connect to MongoLabs.

**Comment by redspirit** [comment] 2015-12-10 17:38
+1

**Comment by tomzaragoza** [comment] 2015-12-12 06:12
Would also love an update on this!

**Comment by douwevdijk** [comment] 2015-12-14 13:25
+1, cannot connect.

**Comment by RaFeNiX** [comment] 2015-12-14 14:36
+1

**Comment by josemarcenaro** [comment] 2015-12-15 00:15
+1

**Comment by sanjaypoyzer** [comment] 2015-12-16 17:42
+1

**Comment by zaptree** [comment] 2015-12-17 01:51
+1

**Comment by gaskar** [comment] 2015-12-20 20:04
+1

**Comment by elpsk** [comment] 2015-12-21 10:10
+1

**Comment by truskovskiyk** [comment] 2015-12-22 14:53
+1

**Comment by zniazi** [comment] 2015-12-23 23:22
+1

**Comment by rhgithub1** [comment] 2015-12-27 15:50
+1

**Comment by DevVersion** [comment] 2015-12-29 23:44
Got the same issue :boom:

**Comment by jgauna** [comment] 2016-01-02 07:19
me too +1

**Comment by sasivarnan** [comment] 2016-01-03 07:04
+1

**Comment by linyo** [comment] 2016-01-07 02:58
me too +1

**Comment by vinguan** [comment] 2016-01-08 17:49
Same Here on mongoldb sandbox

**Comment by rafaelcorreiapoli** [comment] 2016-01-10 15:02
+1

**Comment by davidenq** [comment] 2016-01-10 22:35
Hi all, Robomongo is currently fund-raising to stay alive. If you like the tool, consider supporting its development. See their indiegogo campaign here: https://www.indiegogo.com/projects/save-robomongo#/.

**Comment by ayrilmaz** [comment] 2016-01-15 11:48
+1

**Comment by playnox** [comment] 2016-01-16 15:17
Hey Dmitry Fix the Auth and I'm sure most of us will support your project on Indigogo and etc... ATM this tool is pretty much useless since it's not compatible with MongoLab.

**Comment by ebuah** [comment] 2016-01-23 17:25
@playnox No. Contribute so he gets the time to fix it. Why are people so cheap. He has to spend time away from work and family to do this. The least we can do is support him financially, if Robomongo is that important to us.

**Comment by playnox** [comment] 2016-01-23 17:46
@ebuah He doesn't have to do it personally, it's an open source project... anyone can contribute.
Cheers!

**Comment by anorsich** [comment] 2016-01-23 18:11
@playnox Can you give some more details on what exactly does not work? I am able to connect to the mongolab just fine with [new 0.9.0-RC1 version](http://blog.robomongo.org/robomongo-rc1-for-mac-os-x/)

**Comment by playnox** [comment] 2016-01-23 18:24
@anorsich Thanks for sharing link... got new Ver and everything works fine! please close this ticket

**Comment by josemarcenaro** [comment] 2016-01-23 18:29
Wait! Before closing the ticket ... 0.9.0-RC1 version is only available for Linux and Mac for now (no Windows version). The latest version for windows is 0.8.5 with no support for Mongolab.

Thanks

**Comment by anorsich** [comment] 2016-01-23 19:38
@josemarcenaro No worries, ticket won't be closed before windows version is ready.

**Comment by schetnikovich** [comment] 2016-01-29 16:58
Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-0-9-0-rc3-released), we support MongoDB 3.x, including WiredTiger engine. It means that now you can connect to MongoLab, if you are not using replica sets. Let us know, how it works for you. For any found issues, please create new ticket.

Thank you all for patience!

**Closed by schetnikovich** 2016-01-29 16:58 UTC
Labels: needs repro

**Comment by Crotery** [comment] 2016-02-26 06:29
confirming 9.0 RC4 works nice

**Comment by alokaroracrest** [comment] 2016-03-07 02:13
Mac 10.10.2
0.9.0-RC6
I still see error Authentication failed.. can you please check?

**Comment by vicky-gonsalves** [comment] 2016-03-13 14:31
Yes it worked for me too..

**Comment by powolnymarcel** [comment] 2016-03-23 14:12
Confirmed for me too btw this new robomongo logo is much better :p
