### ISSUE TITLE
Many UI elements are too big with higher DPI % (e.g. 200%)

### ISSUE THREAD

**Issue by pqvst** [paralect/robomongo#1020] opened 2016-02-09 22:53 UTC
Some things look correct, some are way too big, for example:

* "Hey this could be the last releast" is too big
* Query tab titles are too big
* Connection info at the top of each tab is too big
* Table name and execute time is too big
* Pagination numbers are too big
* Create/edit connection dialog elements are too big
* Some other things..

**Comment by anorsich** [comment] 2016-02-10 11:34
@pqvst We will work on the look on the look and feel Robomongo. We love that kind of work! In [RC5](http://blog.robomongo.org/campaign-is-over-robomongo-is-not/), we removed advertisement message since the campaign is over already. So first thing is fixed already :)

**Comment by simsekgokhan** [comment] 2016-08-10 15:37
Hi @pqvst , could you tell us about the OS version and screen resolution that you experience the problem. A screenshot also would help a lot on understanding and fixing your problem.

In Robobomongo RC10, for better High DPI support, we have updated Robomongo to use Qt latest version 5.7. Besides Qt 5.7 transition, we have implemented many additional fine-grained enhancements for the cases where for Qt cannot handle correctly. (can be seen on our RC10 blog soon)

You can also see some issues already reported and fixed here: 
HiDPI screens support #1104
https://github.com/paralect/robomongo/issues/1104

**Comment by pqvst** [comment] 2016-08-12 07:23
Same as #1104. I use Windows 10 x64 with 3840 x 2160 resolution.

**Comment by simsekgokhan** [comment] 2016-08-12 10:33
The problem is we are unable to reproduce the issue, we have tested with 3840*2160 on win7 and win10, it works fine. 

Can you provide a screenshot of your problem and give us more information about your environment? (your screen resolution, monitor model etc..)

We are trying to reproduce with no luck, if we can reproduce the issue, finding a solution will be much easier.

**Comment by pqvst** [comment] 2016-08-12 12:15
Lately I haven't been using DPI scaling since I've had issues in other apps as well. I just tried again with RC9, 3840x2160, 200% scaling. Everything is looking OK, except maybe the toolbar buttons are too small.

![adsf](https://cloud.githubusercontent.com/assets/4990657/17620946/4ab6aba2-6090-11e6-9c41-539907d715f4.png)

**Comment by simsekgokhan** [comment] 2016-08-12 13:39
Thanks a lot for the screenshot.
We have High-DPI enhancements in RC10 exactly for this small icons and text alignment problems. 
Please see:

![7 hidpi_all_v6](https://cloud.githubusercontent.com/assets/19390749/17623787/80887a70-60aa-11e6-8cc0-496652389781.png)

**Comment by juliashibalko** [comment] 2016-10-07 16:09
Hi @pqvst! Could you please check issue with Robomongo 0.9.0-RC10 if possible? We implemented better HiDPI support there and transited to Qt5.7. So I hope it will solve the problem.
Please see download site https://robomongo.org/download and feature list http://blog.robomongo.org/robomongo-rc10/

**Comment by pqvst** [comment] 2016-10-09 14:21
@juliashibalko looks like it's fixed :)

**Comment by juliashibalko** [comment] 2016-10-10 10:37
@pqvst Great to hear that!
I'm closing this issue as fixed. Thank you!

**Closed by juliashibalko** 2016-10-10 10:37 UTC
Labels: cosmetic, enhancement, os-windows
