### ISSUE TITLE
Editing an existing document converts Int32 fields to scientific notation

### ISSUE THREAD

**Issue by sfelf** [paralect/robomongo#817] opened 2015-03-23 21:00 UTC
We use robomongo's edit feature often to update data and ran into a problem after upgrading to version 0.8.5. Data that is stored in MongoDB as an `Int32` is displayed on the edit document page in scientific notation. The really negative side effect here is if you don't notice it and save the changes to the document all `Int32` fields are converted to Doubles and fidelity can be lost.

To reproduce try the following:

```
use int_test;
db.int_test.update({}, {$set: {sample: NumberInt(1427137266)}});
db.int_test.find();
```

Then when you right click on the inserted document and select edit document the following is displayed.

```
{
    "_id" : ObjectId("551064dce6b5e75c64e25922"),
    "sample" : 1.42714e+009
}
```

If you click save the original value of 1427137266 is converted to 1427140000.

We are using Windows 7 (64 bit) and our MongoDB servers are running version 2.6.8.

**Comment by stennie** [comment] 2015-03-23 23:25
@sfelf Were you previously using Robomongo 0.8.4 without issue? Wondering if perhaps related to the change for #622.

**Comment by sfelf** [comment] 2015-03-23 23:50
@stennie I did not have this issue with 0.8.4 and have reverted back to 0.8.4 as a result of this issue.

**Comment by stennie** [comment] 2015-03-24 01:12
@sfelf Thanks for confirming. Will test it out and aim to get a bugfix in for 0.8.6, if possible.

**Comment by stennie** [comment] 2015-04-15 06:42
Duplicate of #831

**Closed by stennie** 2015-04-15 06:42 UTC
Labels: bug, duplicate
