### ISSUE TITLE
Mac OSX: External monitor issue (crash)

### ISSUE THREAD

**Issue by antonimmo** [paralect/robomongo#518] opened 2014-04-18 06:37 UTC
This is my escenario:

1. My computer is on
2. I open Robomongo in the main screen and move it to the second one
3. Now I unplug the second display and Robomongo goes to the first screen. Everything is fine here.
4. Finally I plug back the same external monitor, I do nothing else, and Robomongo crashes. 

When it happens to me again, I will post the trace here.

Note: In OSX 10.8, the secondary desktops fuse to the primaries when I unplug the external monitor. In OSX 10.9, the secondaries become new primaries and they are secondaries again when I plug the monitor again. In both cases I have the same error, Robomongo crashes the same way.

**Comment by stennie** [comment] 2015-03-14 01:00
@antonimmo @amstree Can you retest this with the 0.8.5 release preview: #778? I'm wondering if updating to Qt 5.3.2 may have resolved the problem.

I have so far been unable to reproduce the issue on OS X 10.10.2 with an external monitor attached (via Thunderbolt => HDMI if that makes a diff).

Thanks!

**Comment by petek** [comment] 2015-03-14 01:21
I was able to crash 0.8.4 but not this 0.8.5 preview release.

**Comment by stennie** [comment] 2015-03-14 06:36
@petek Thanks for confirming. I can't reproduce the issue either, so will assume this has been fixed in the 0.8.5 release.

If anyone is still experiencing problems with 0.8.5, please open a new issue with details.

Thanks!

**Closed by stennie** 2015-03-14 06:36 UTC
Labels: needs repro, os-mac

**Comment by antonimmo** [comment] 2015-03-17 16:10
I confirm that it's solved for me in the 0.8.5 version

**Comment by stennie** [comment] 2015-03-17 16:13
@antonimmo Excellent, thanks for confirming :)

**Comment by amstree** [comment] 2015-04-07 13:54
thanks @stennie 
This is working perfectly! love the new gui.
