### ISSUE TITLE
Huge list of collections loading very slow

### ISSUE THREAD

**Issue by destromas1** [paralect/robomongo#1014] opened 2016-02-05 16:14 UTC
WINDOWS 8.1

When I connect to remote MongoServer,when a lot data there,it does not show the Collection List,Goes hanged

Then I started MongoChef , there Worked fine .

I like RoboMongo A lot , please fix this issue , its a Major one.I can not simply see any collection any data!

**Comment by anorsich** [comment] 2016-02-05 17:53
@destromas1 Thank you for submitting the issue! To help us reproduce it, could you provide some more details. How many collections your database have? Does it have authentication? What version of Mongodb you use?

**Comment by destromas1** [comment] 2016-02-05 18:58
![image](https://cloud.githubusercontent.com/assets/602127/12855978/b48f4902-cc6c-11e5-870d-b7d00179fc40.png)

**Comment by destromas1** [comment] 2016-02-05 18:59
![image](https://cloud.githubusercontent.com/assets/602127/12856018/e79b7f8c-cc6c-11e5-9186-ed0cc23f9f2a.png)

**Comment by destromas1** [comment] 2016-02-05 19:07
Its from MongoChef , u can see DB details.Its staging Server , We mainly generate Collections in runtime . So in PRODUCTION , There will be thousands of collections @anorsich  

![image](https://cloud.githubusercontent.com/assets/602127/12856167/b0150ce4-cc6d-11e5-9fd5-2d1cf8d3cd2c.png)

**Comment by destromas1** [comment] 2016-02-05 19:17
![image](https://cloud.githubusercontent.com/assets/602127/12856488/5c42ff20-cc6f-11e5-89a7-50cce72877e9.png)

**Comment by destromas1** [comment] 2016-02-05 19:20
Its from MongoChef , u can see DB details.Its staging Server , We mainly generate Collections in runtime.
So in PRODUCTION , There will be thousands of collections @anorsich

![image](https://cloud.githubusercontent.com/assets/602127/12856578/d44999c0-cc6f-11e5-8d9e-9212b2f1b28f.png)

**Comment by destromas1** [comment] 2016-02-05 19:22
Need to tell you that , after a lot time 5-10 Minutes , I can see the collection List in RoboMongo whether , in MongoChef I can see in 4-5 Seconds!

**Comment by anorsich** [comment] 2016-02-05 19:42
@destromas1 Awesome, thank you for such detailed response! Now we now what to improve.

**Comment by destromas1** [comment] 2016-02-05 19:58
@anorsich  Welcome mate !  I am also Core Developer and I like to use Robomongo , dont wanna use paid MongoChef , Thats why I also want you get the exact help from me to resolve the issue.

We are trying to build NextGen Webinar platform where , we might have thousands of Collections at a time , as we generate collections in runtime .

Just few things more to share-
---> When Mongo Database connected to Robomongo , it should only query the Collection names to show in the Left Nav Bar , and then when user clicks the Specific Collection , then query the Documents of that Collection. It might trying to get the Data also in first time (Just assumption)

Hope to get fixed this soon ! :)

**Comment by m--stein** [comment] 2016-02-05 22:18
I guess its the same issue: #730

**Comment by destromas1** [comment] 2016-02-05 22:20
#

**Comment by destromas1** [comment] 2016-02-05 22:22
@m--stein 

Seems similar , but in my case , I had a lot slower , I mean HANG . It shows Data after more than 15 minutes around sometimes . U can not wait !

**Comment by anorsich** [comment] 2016-02-15 08:06
@destromas1 Great news! This issue has been fixed in the latest RC6 build of Robomongo. If you want to try it out and help us with testing - just signup at [robomongo](https://robomongo.org/signup) and send a message to support that you want to help us test the latest release - we will give it to you right away!

**Comment by anorsich** [comment] 2016-02-16 19:48
@destromas1 Since this issue was fixed in the latest RC-6 release I am going to close this issue. If it won't work for you -- feel free to reopen!

**Closed by anorsich** 2016-02-16 19:48 UTC

**Comment by destromas1** [comment] 2016-02-16 19:50
@anorsich Awesome , Will have a look!
