### ISSUE TITLE
Can't Edit Shell Commands

### ISSUE THREAD

**Issue by dr3x** [paralect/robomongo#601] opened 2014-06-17 17:40 UTC
I can cut & paste into the shell command line but can't edit the text there; used to be able to do that.

Robomongo 0.8.4

**Comment by stennie** [comment] 2015-03-12 01:50
I can't reproduce this with Centos 6.6 / Robomongo 0.8.4. Perhaps there are some different libs on CentOS 6.2?

Given the age of this issue I'm going to close it. Please feel free to open a new issue with updated details if you are still seeing the problem.

Also FYI, 0.8.5 is on the way (watch #783 for a preview of the RPM if you'd like to help test). 

Thanks!

**Closed by stennie** 2015-03-12 01:50 UTC
Labels: cannot reproduce, os-linux
