### ISSUE TITLE
view referenced documents

### ISSUE THREAD

**Issue by guido577** [paralect/robomongo#702] opened 2014-12-01 07:44 UTC
Is it possible to view a referenced document in tree view directly instead of displaying $ref and $id fields? Or have I missed a feature of robomongo?
Example: field owner in attached image:
![reference](https://cloud.githubusercontent.com/assets/10020589/5242555/c8b466dc-7935-11e4-8fba-3fa9a79fdcc1.PNG)
 That would be very helpful!

**Comment by stennie** [comment] 2015-03-10 13:11
@guido577 Noticed this is a duplicate of #377, so closing.

**Closed by stennie** 2015-03-10 13:11 UTC
Labels: duplicate
