### ISSUE TITLE
Build failure Xubuntu 14.04

### ISSUE THREAD

**Issue by martinhbramwell** [paralect/robomongo#750] opened 2015-02-03 13:47 UTC
yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$ make --version
      GNU Make 3.81
      Copyright (C) 2006  Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.
      There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
      PARTICULAR PURPOSE.

      This program built for x86_64-pc-linux-gnu
      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$ gcc --version
      gcc (Ubuntu 4.8.2-19ubuntu1) 4.8.2
      Copyright (C) 2013 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$ g++ --version
      g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2
      Copyright (C) 2013 Free Software Foundation, Inc.
      This is free software; see the source for copying conditions.  There is NO
      warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$ qmake --version
      QMake version 3.0
      Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu
      yourself@mdev:~/tmp/robomongo/target$ 
      yourself@mdev:~/tmp/robomongo/target$ 
      yourself@mdev:~/tmp/robomongo/target$ cmake --version
      cmake version 3.1.20150203-g460f7

      CMake suite maintained and supported by Kitware (kitware.com/cmake).
      yourself@mdev:~/tmp/robomongo/target$ 
      yourself@mdev:~/tmp/robomongo/target$ 
      yourself@mdev:~/tmp/robomongo/target$ scons --version
      SCons by Steven Knight et al.:
	      script: v2.3.0, 2013/03/03 09:48:35, by garyo on reepicheep
	      engine: v2.3.0, 2013/03/03 09:48:35, by garyo on reepicheep
	      engine path: ['/usr/lib/scons/SCons']
      Copyright (c) 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013 The SCons Foundation
      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$ cmake .. -DOS_ARC=64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
      -- The C compiler identification is GNU 4.8.2
      -- The CXX compiler identification is GNU 4.8.2
      -- Check for working C compiler: /usr/bin/cc
      -- Check for working C compiler: /usr/bin/cc -- works
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Check for working CXX compiler: /usr/bin/c++
      -- Check for working CXX compiler: /usr/bin/c++ -- works
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- CMAKE_SYSTEM_PROCESSOR: x86_64
      -- CMAKE_SYSTEM: Linux-3.13.0-44-generic
      -- CMAKE_BUILD_TYPE: RELEASE
      -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1f") 
      -- Qt5 found
      Using setting for DYNAMIC run-time
      CMake Warning (dev) at src/third-party/qscintilla/Qt4Qt5/CMakeLists.txt:2 (project):
        Policy CMP0048 is not set: project() command manages VERSION variables.
        Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
        command to set the policy and suppress this warning.

        The following variable(s) would be set to empty:

          PROJECT_VERSION
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Qt5 found
      Using setting for DYNAMIC run-time
      CMake Warning (dev) at src/third-party/mongodb/src/third_party/js-1.7/CMakeLists.txt:2 (PROJECT):
        Policy CMP0048 is not set: project() command manages VERSION variables.
        Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
        command to set the policy and suppress this warning.

        The following variable(s) would be set to empty:

          PROJECT_VERSION
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Could NOT find BZip2 (missing:  BZIP2_LIBRARIES BZIP2_INCLUDE_DIR) 
      -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
      CMake Warning at src/third-party/mongodb/src/third_party/pcre-8.30/CMakeLists.txt:71 (FIND_PACKAGE):
        By not providing "FindReadline.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "Readline",
        but CMake did not find one.

        Could not find a package configuration file provided by "Readline" with any
        of the following names:

          ReadlineConfig.cmake
          readline-config.cmake

        Add the installation prefix of "Readline" to CMAKE_PREFIX_PATH or set
        "Readline_DIR" to a directory containing one of the above files.  If
        "Readline" provides a separate development package or SDK, be sure it has
        been installed.

      -- Looking for dirent.h
      -- Looking for dirent.h - found
      -- Looking for stdint.h
      -- Looking for stdint.h - found
      -- Looking for inttypes.h
      -- Looking for inttypes.h - found
      -- Looking for sys/stat.h
      -- Looking for sys/stat.h - found
      -- Looking for sys/types.h
      -- Looking for sys/types.h - found
      -- Looking for unistd.h
      -- Looking for unistd.h - found
      -- Looking for windows.h
      -- Looking for windows.h - not found
      -- Looking for C++ include type_traits.h
      -- Looking for C++ include type_traits.h - not found
      -- Looking for C++ include bits/type_traits.h
      -- Looking for C++ include bits/type_traits.h - not found
      -- Looking for bcopy
      -- Looking for bcopy - found
      -- Looking for memmove
      -- Looking for memmove - found
      -- Looking for strerror
      -- Looking for strerror - found
      -- Looking for strtoll
      -- Looking for strtoll - found
      -- Looking for strtoq
      -- Looking for strtoq - found
      -- Looking for _strtoi64
      -- Looking for _strtoi64 - not found
      -- Looking for stddef.h
      -- Looking for stddef.h - found
      -- Check size of long long
      -- Check size of long long - done
      -- Check size of unsigned long long
      -- Check size of unsigned long long - done
      -- 
      -- 
      -- PCRE configuration summary:
      -- 
      --   Install prefix .................. : /home/yourself/tmp/robomongo/target/install
      --   C compiler ...................... : /usr/bin/cc
      --   C++ compiler .................... : /usr/bin/c++
      --   C compiler flags ................ :  -m64 -O3 -DNDEBUG
      --   C++ compiler flags .............. :  -fPIC -m64 -O3 -DNDEBUG
      -- 
      --   Build 8 bit PCRE library ........ : ON
      --   Build 16 bit PCRE library ....... : OFF
      --   Build C++ library ............... : ON
      --   Enable JIT compiling support .... : OFF
      --   Enable UTF support .............. : OFF
      --   Unicode properties .............. : OFF
      --   Newline char/sequence ........... : LF
      --   \R matches only ANYCRLF ......... : OFF
      --   EBCDIC coding ................... : OFF
      --   Rebuild char tables ............. : OFF
      --   No stack recursion .............. : OFF
      --   POSIX mem threshold ............. : 10
      --   Internal link size .............. : 2
      --   Match limit ..................... : 10000000
      --   Match limit recursion ........... : MATCH_LIMIT
      --   Build shared libs ............... : OFF
      --   Build static libs ............... : ON
      --   Build pcregrep .................. : OFF
      --   Enable JIT in pcregrep .......... : ON
      --   Buffer size for pcregrep ........ : 20480
      --   Build tests (implies pcretest  .. : OFF
      --                and pcregrep)
      --   Link pcregrep with libz ......... : ON
      --   Link pcregrep with libbz2 ....... : None
      --   Link pcretest with libreadline .. : None
      -- 
      CMake Warning (dev) at src/third-party/mongodb/src/third_party/boost/CMakeLists.txt:2 (project):
        Policy CMP0048 is not set: project() command manages VERSION variables.
        Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
        command to set the policy and suppress this warning.

        The following variable(s) would be set to empty:

          PROJECT_VERSION
      This warning is for project developers.  Use -Wno-dev to suppress it.

      CMake Warning (dev) at src/third-party/mongodb/src/third_party/libssh2/CMakeLists.txt:2 (project):
        Policy CMP0048 is not set: project() command manages VERSION variables.
        Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
        command to set the policy and suppress this warning.

        The following variable(s) would be set to empty:

          PROJECT_VERSION
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so;/usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.1f") 
      CMake Warning (dev) at /usr/lib/x86_64-linux-gnu/cmake/Qt5Core/Qt5CoreMacros.cmake:224 (configure_file):
        configure_file called with unknown argument(s):

         COPY_ONLY

      Call Stack (most recent call first):
        cmake/integrate-qt.cmake:123 (QT5_ADD_RESOURCES)
        src/CMakeLists.txt:314 (QTX_ADD_RESOURCES)
      This warning is for project developers.  Use -Wno-dev to suppress it.

      -- Qt libs to install /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.2.1;/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.2.1;/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.2.1;/usr/lib/x86_64-linux-gnu/libQt5DBus.so.5.2.1
      -- Deployng /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so plugin for Release
      -- Deployng /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk2.so plugin for Release
      -- Deployng /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqgif.so plugin for Release
      -- Could not deploy , required path: icuuc49, plugin for Release
      -- Could not deploy , required path: icudata49, plugin for Release
      -- Could not deploy , required path: icui18n49, plugin for Release
      -- Could not deploy , required path: icuuc51, plugin for Release
      -- Could not deploy , required path: icudata51, plugin for Release
      -- Could not deploy , required path: icui18n51, plugin for Release
      -- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
      -- Looking for include file pthread.h
      -- Looking for include file pthread.h - found
      -- Looking for pthread_create
      -- Looking for pthread_create - not found
      -- Looking for pthread_create in pthreads
      -- Looking for pthread_create in pthreads - not found
      -- Looking for pthread_create in pthread
      -- Looking for pthread_create in pthread - found
      -- Found Threads: TRUE  
      -- CPACK_PACKAGE_FILE_NAME: robomongo-0.8.5-x86_64
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /home/yourself/tmp/robomongo/target
      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$ 
      yourself@mdev:~/tmp/robomongo/target$ make
      Scanning dependencies of target VersionConf
      [  0%] Generating ../robomongo/robomongo.desktop
      [  0%] Built target VersionConf
      Scanning dependencies of target libssh2_third_party
      [  0%] Building C object src/third-party/mongodb/src/third_party/libssh2/CMakeFiles/libssh2_third_party.dir/src/global.c.o
      [  0%] Building C object src/third-party/mongodb/src/third_party/libssh2/CMakeFiles/libssh2_third_party.dir/src/session.c.o
                          :                    :                    :
      [  2%] Building C object src/third-party/mongodb/src/third_party/libssh2/CMakeFiles/libssh2_third_party.dir/src/mac.c.o
                          :                    :                    :
      [  4%] Generating moc_SciClasses.cpp
      [  4%] Generating Qsci/moc_qsciglobal.cpp
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/Qt4Qt5/Qsci/qsciglobal.h:0: Note: No relevant classes found. No output generated.
      [  4%] Generating Qsci/moc_qsciscintilla.cpp
                          :                    :                    :
      [  5%] Generating Qsci/moc_qscicommand.cpp
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/Qt4Qt5/Qsci/qscicommand.h:0: Note: No relevant classes found. No output generated.
      [  5%] Generating Qsci/moc_qscicommandset.cpp
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/Qt4Qt5/Qsci/qscicommandset.h:0: Note: No relevant classes found. No output generated.
      [  5%] Generating Qsci/moc_qscidocument.cpp
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/Qt4Qt5/Qsci/qscidocument.h:0: Note: No relevant classes found. No output generated.
      [  5%] Generating Qsci/moc_qscilexer.cpp
      [  6%] Generating Qsci/moc_qscilexeravs.cpp
                          :                    :                    :
      [ 11%] Generating Qsci/moc_qscimacro.cpp
      [ 12%] Generating Qsci/moc_qsciprinter.cpp
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/Qt4Qt5/Qsci/qsciprinter.h:0: Note: No relevant classes found. No output generated.
      [ 12%] Generating Qsci/moc_qscistyle.cpp
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/Qt4Qt5/Qsci/qscistyle.h:0: Note: No relevant classes found. No output generated.
      [ 12%] Generating Qsci/moc_qscistyledtext.cpp
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/Qt4Qt5/Qsci/qscistyledtext.h:0: Note: No relevant classes found. No output generated.
      Scanning dependencies of target qscintilla2
      [ 12%] Building CXX object src/third-party/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/Qsci/moc_qsciglobal.cpp.o
                          :                    :                    :
      [ 47%] Building CXX object src/third-party/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/__/src/Editor.cpp.o
      [ 47%] Building CXX object src/third-party/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/__/src/ExternalLexer.cpp.o
      In file included from /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:24:0:
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:28:30: error: expected ‘)’ before ‘*’ token
       typedef void*(EXT_LEXER_DECL *GetLexerFunction)(unsigned int Index);
                                    ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:28:30: error: expected initializer before ‘*’ token
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:29:29: error: expected ‘)’ before ‘*’ token
       typedef int (EXT_LEXER_DECL *GetLexerCountFn)();
                                   ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:30:30: error: expected ‘)’ before ‘*’ token
       typedef void (EXT_LEXER_DECL *GetLexerNameFn)(unsigned int Index, char *name, int buflength);
                                    ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:31:45: error: expected ‘)’ before ‘*’ token
       typedef LexerFactoryFunction(EXT_LEXER_DECL *GetLexerFactoryFunction)(unsigned int Index);
                                                   ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:36:2: error: ‘GetLexerFactoryFunction’ does not name a type
        GetLexerFactoryFunction fneFactory;
        ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:47:27: error: ‘GetLexerFactoryFunction’ has not been declared
        virtual void SetExternal(GetLexerFactoryFunction fFactory, int index);
                                 ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.h: In constructor ‘ExternalLexerModule::ExternalLexerModule(int, LexerFunction, const char*, LexerFunction)’:
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.h:42:3: error: class ‘ExternalLexerModule’ does not have any field named ‘fneFactory’
         fneFactory(0) {
         ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp: At global scope:
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:38:39: error: variable or field ‘SetExternal’ declared void
       void ExternalLexerModule::SetExternal(GetLexerFactoryFunction fFactory, int index) {
                                             ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:38:39: error: ‘GetLexerFactoryFunction’ was not declared in this scope
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:38:73: error: expected primary-expression before ‘int’
       void ExternalLexerModule::SetExternal(GetLexerFactoryFunction fFactory, int index) {
                                                                               ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp: In constructor ‘LexerLibrary::LexerLibrary(const char*)’:
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:59:3: error: ‘GetLexerCountFn’ was not declared in this scope
         GetLexerCountFn GetLexerCount = (GetLexerCountFn)(sptr_t)lib->FindFunction("GetLexerCount");
         ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:59:19: error: expected ‘;’ before ‘GetLexerCount’
         GetLexerCountFn GetLexerCount = (GetLexerCountFn)(sptr_t)lib->FindFunction("GetLexerCount");
                         ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:61:7: error: ‘GetLexerCount’ was not declared in this scope
         if (GetLexerCount) {
             ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:66:4: error: ‘GetLexerNameFn’ was not declared in this scope
          GetLexerNameFn GetLexerName = (GetLexerNameFn)(sptr_t)lib->FindFunction("GetLexerName");
          ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:66:19: error: expected ‘;’ before ‘GetLexerName’
          GetLexerNameFn GetLexerName = (GetLexerNameFn)(sptr_t)lib->FindFunction("GetLexerName");
                         ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:67:4: error: ‘GetLexerFactoryFunction’ was not declared in this scope
          GetLexerFactoryFunction fnFactory = (GetLexerFactoryFunction)(sptr_t)lib->FindFunction("GetLexerFactory");
          ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:67:28: error: expected ‘;’ before ‘fnFactory’
          GetLexerFactoryFunction fnFactory = (GetLexerFactoryFunction)(sptr_t)lib->FindFunction("GetLexerFactory");
                                  ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:76:33: error: ‘GetLexerName’ was not declared in this scope
           GetLexerName(i, lexname, 100);
                                       ^
      /home/yourself/tmp/robomongo/src/third-party/qscintilla/src/ExternalLexer.cpp:94:22: error: ‘fnFactory’ was not declared in this scope
           lex->SetExternal(fnFactory, i);
                            ^
      make[2]: *** [src/third-party/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/__/src/ExternalLexer.cpp.o] Error 1
      make[1]: *** [src/third-party/qscintilla/Qt4Qt5/CMakeFiles/qscintilla2.dir/all] Error 2
      make: *** [all] Error 2
      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$
      yourself@mdev:~/tmp/robomongo/target$

**Comment by stennie** [comment] 2015-03-11 12:23
Hitting the same error with Ubuntu 14.04 (noticed this is a dupe of #733 which has a more descriptive subject).

**Closed by stennie** 2015-03-11 12:23 UTC
Labels: bug, os-linux
