### ISSUE TITLE
Copy collection does not work

### ISSUE THREAD

**Issue by DQvsRA** [paralect/robomongo#911] opened 2015-07-08 15:58 UTC
I try to copy collection from remote EC2 mongoDB instance to my local machine, but have no result, nothing is happen. Why?

**Comment by anorsich** [comment] 2016-02-03 07:44
@DQvsRA Thank you for reporting this issue. Copy collection functionality does not stable at the moment. I am closing this issue as duplicate of #398. Please use it for reference to track implementation progress.

**Closed by anorsich** 2016-02-03 07:44 UTC
Labels: needs repro
