### ISSUE TITLE
Not working for 2.8 rc with WiredTiger as storage Engine 

### ISSUE THREAD

**Issue by pablocaselas** [paralect/robomongo#707] opened 2014-12-04 12:50 UTC
It connects okay, but I am not able to list collections in databases.

**Comment by sallgeud** [comment] 2015-02-06 15:53
Given our experience with wiredTiger, somewhat slower single-threaded performance, minimal increase in cpu usage, greatly improved multi-threaded performance, 88-92% reduction in memory and disk usage, I can't imagine we'd stay with mmapv1. For those joining the game after 3.0, it's hard to imagine any would choose mmap unless that 2-8% single-threaded performance is absolutely needed versus disk & memory.

**Comment by ChALkeR** [comment] 2015-02-15 16:24
`db.getCollectionNames()` and `db.printCollectionStats()` return empty results in robomongo, but work with native `mongo` client.

**Comment by ChALkeR** [comment] 2015-02-15 16:29
It seems that while the collection list is somewhy not working, executing per-collection commands work just fine, so Robomongo is still usable with 3.0 + wiredTiger.
For example, running `db.yourCollectionName.find()` gives you a valid result (as it should).

**Comment by stennie** [comment] 2015-02-16 02:20
@ChALkeR As noted, there are are some changes required for full compatibility with WiredTiger / MongoDB 3.0. Listing collections & indexes in particular is not supported for WiredTiger because there is a new API in 3.0. Working on it, though :).

**Comment by ngonpham** [comment] 2015-03-13 00:37
Yeah, am also waiting. Look forward to the new update to support WiredTiger :+1:

**Comment by cbratschi** [comment] 2015-03-19 15:45
@stennie any ETA? We migrated to WiredTiger and would like to continue using Robomongo.

**Comment by stennie** [comment] 2015-03-20 03:17
@cbratschi No specific ETA yet beyond "as soon as I can". I'm also using MongoDB 3.0 and really need WiredTiger support (as well as updated shell) to make Robomongo useful. Actively working through build issues at the moment and will update related Github issues when there's something committed.

Thanks!

**Comment by jeffwrule** [comment] 2015-04-20 18:43
We prefer this tool over mongo hub, but have to ditch it for now until you fix support for wiredTiger engine.  We have switched our entire database to wiredTiger as of April.

**Comment by firla** [comment] 2015-04-26 13:05
Same here: +1 for WiredTiger support. Please integrate it asap. Thank you.

**Comment by thardy** [comment] 2015-05-01 20:43
Came here looking for wiredtiger support as well.

**Comment by pixelhandler** [comment] 2015-05-08 01:25
Yeah need that wired tiger support here too :)

**Comment by nilslahr** [comment] 2015-05-29 19:17
how hard is it to update to WiredTiger?  Can anyone else make the changes and recompile?

**Comment by notrix** [comment] 2015-06-15 12:23
:+1:

**Comment by MatthiasJost** [comment] 2015-06-19 07:33
Same situation here, disappointed that WiredTiger is not yet supported ;-)

**Comment by marcus-ahle** [comment] 2015-06-22 14:11
:+1:

**Comment by KonstantinZvyagin** [comment] 2015-06-26 09:05
Still not working ....

**Comment by 4lifedev** [comment] 2015-06-29 18:30
Also waiting for support.

**Comment by BHare1985** [comment] 2015-07-02 19:57
Our company is about to buy 10 licenses for about $1000 from a competitor all because robomongo cannot support WiredTiger. No commits since April, I consider this project dead. :-1

**Comment by chydak** [comment] 2015-07-02 19:59
We had to do that as well.

**Comment by mikeckennedy** [comment] 2015-07-02 20:27
@BHare1985 what product are you considering?

**Comment by pixelhandler** [comment] 2015-07-02 20:39
I did a trial license with "3T MongoChef" and was impressed.

**Comment by mikeckennedy** [comment] 2015-07-02 20:51
Thanks @pixelhandler Interesting. What surprises me is that this is even a problem. Doesn't the C++ driver that Robomongo is using handle any variance between MMF & WiredTiger?

**Comment by sallgeud** [comment] 2015-07-02 20:57
It does, mike... but robomongo doesn't appear to use that driver in the way you'd expect

**Comment by mikeckennedy** [comment] 2015-07-02 21:41
Right, figured it was something like this. I suspect they have a good reason for that but bummer still.

**Comment by MatthiasJost** [comment] 2015-07-03 08:57
We are using MongoChef here too. Also other projects like MongoVUE do not offer real MongoDB 3 support (WiredTiger). This issue is now open since December!

**Comment by cbratschi** [comment] 2015-07-14 10:21
Also switched to MongoChef in the meantime. Thanks for the recommendation, this is a very good tool.

**Comment by nickarnold** [comment] 2015-10-14 20:41
@MatthiasJost Thanks for the heads up on MongoChef! One can always just use CLI clients, but sometimes these GUIs really come in handy. I can confirm MongoChef is working well on OSX 10.10 with Mongo 3.x and the wiredTiger engine.

**Comment by fontanon** [comment] 2015-11-10 09:09
Please add wiredTiger support.

**Comment by syzer** [comment] 2015-11-23 20:15
+1

**Comment by diegolaciar** [comment] 2016-01-21 13:42
+1 for WiredTiger support

**Comment by anorsich** [comment] 2016-01-22 18:16
@diegolaciar Newest version of the Robomongo already support WigerTiger & mongodb 3+. Only linux and osx packages available at the moment, windows package coming soon. More details are [here](http://blog.robomongo.org/robomongo-rc1-with-full-support-for-mongodb-3/) and [here](http://blog.robomongo.org/robomongo-rc1-for-mac-os-x/)

**Comment by yallie** [comment] 2016-01-23 10:39
@anorsich That's great news! Can't wait for Windows package!

**Comment by schetnikovich** [comment] 2016-01-25 21:38
Robomongo 0.9.0 RC2 just [released for all platforms](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux), including Windows. Support for WiredTiger engine built-in. 

Let us know, how it works for you.

**Comment by yallie** [comment] 2016-01-26 15:26
@schetnikovich Thanks a lot!
Robomongo works great with Wired Tiger storage on Windows!
:+1:

**Comment by schetnikovich** [comment] 2016-01-27 17:11
[Robomongo 0.9.0 RC2](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/) supports MongoDB 3.x and WiredTiger engine. For any found issues, please create new ticket.

**Closed by schetnikovich** 2016-01-27 17:11 UTC
Labels: enhancement
