### ISSUE TITLE
Robomongo not supporting wiredtiger storageengine

### ISSUE THREAD

**Issue by inuskmulla** [paralect/robomongo#939] opened 2015-09-10 10:31 UTC
Robomongo not supporting wiredtiger storageengine, will you please give support for this. when connected to storage engine , it is not showing collections, and also data in collection.
Please reply ASAP.

**Comment by ApfelUser** [comment] 2015-09-10 10:35
@inuskmulla This project is dead, just so you know. Nobody is answering since months. You should've looked through the existing issues before opening this.

**Comment by sleske** [comment] 2015-09-10 12:05
Anyway, this is a dupe of #707 , so can be closed as a duplicate.
I don't have the rights to close it, so someone else will have to.

**Comment by schetnikovich** [comment] 2016-01-27 17:10
[Robomongo 0.9.0 RC2](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/) supports MongoDB 3.x and WiredTiger engine. For any found issues, please create new ticket.

**Closed by schetnikovich** 2016-01-27 17:10 UTC
