### ISSUE TITLE
'Unable to authorize' when connect to mongolab sandbox

### ISSUE THREAD

**Issue by CrisLi** [paralect/robomongo#949] opened 2015-09-25 05:08 UTC
```
2015-09-25 13:03:14: Settings saved to: C:/Users/bli2/.config/robomongo/robomongo.json
2015-09-25 13:04:48: Connecting to ds041663.mongolab.com:41663...
2015-09-25 13:04:51: Settings saved to: C:/Users/bli2/.config/robomongo/robomongo.json
2015-09-25 13:04:51: connect failed
2015-09-25 13:04:54: Unable to authorize
```
When I connect to mongolab, I got 'Unable to authorize' error. I do input the correct username and password. Besides, I can connect to my mongolab sandbox via Node application.

**Comment by jfha73** [comment] 2015-09-30 16:13
I'm getting the same message when trying to connect to MongoDB on MongoLab.

I can also connect using CLI and even my own PHP script.

**Comment by sureshsachin** [comment] 2015-10-01 07:27
I'm getting the same message when trying to connect to MongoDB on MongoLab.



![robomongo_error](https://cloud.githubusercontent.com/assets/14920608/10215050/e09f656c-683b-11e5-8595-48b494ca3572.jpg)

**Comment by vastbinderj** [comment] 2015-10-01 07:30
This stopped working for me today as well.  However I can still get to my 2.6 databases..

**Comment by sureshsachin** [comment] 2015-10-01 07:30
using Robomongo and NOSqlViewer as gui tools.on both same error is displayed.

**Comment by srihari-sridharan** [comment] 2015-10-01 11:12
This may be due to the fact that MongoLabs have upgraded to Mongo 3.0. Please check mongolab home page for information pertaining to this update.

"On Wednesday September 30 starting at 10:00 am PDT / 5:00 pm UTC, we'll be upgrading all free Sandbox plan databases running MongoDB 2.6 to MongoDB 3.0 and all for-pay Shared plan databases running MongoDB 2.4 to MongoDB 2.6. Visit our Documentation Portal for critical details about these version upgrades."

**Comment by johnschult** [comment] 2015-10-01 15:44
+1 Using 0.8.4 and connecting to `mongod 3.0.5`

**Comment by spoike** [comment] 2015-10-03 03:47
Ditto for me. Possibly related to or duplicate of #824

**Comment by DarthYogurt** [comment] 2015-10-04 09:19
This also stopped working for me a few days ago. On 3.0.6

**Comment by Alveoli** [comment] 2015-10-05 10:58
+1 same screen as @sureshsachin 
Stopped working today.  I'm sure it was working before with the same username/password.  I didn't touch Robomongo at all. Has Mongolab made some changes?

**Comment by srihari-sridharan** [comment] 2015-10-05 11:46
This is possibly due to the Mongo Lab upgrade to 3.0!

**Comment by vastbinderj** [comment] 2015-10-05 16:35
Is there any work still happening on Robomongo?  It seems like it has been more than a year since the last commit and no sign of work happening on 0.9.x and the move to v8...

**Comment by jfha73** [comment] 2015-10-09 13:17
I believe this is cause by Mongolab having the authentication mechanism set to use SCRAM-SHA-1 when they upgraded to MongoDB 3.0

**Comment by Alveoli** [comment] 2015-10-11 13:16
Yes thanks confirmed with Mongolab support. Only way round is to either get your own instance with them and run at version 2... or use another mongo client :(

**Comment by philcruz** [comment] 2015-11-07 04:02
I'm running into this as well.

**Comment by parallaxisjones** [comment] 2015-11-10 15:39
I was running into the same issue logging into the mongo CLI shell

**Comment by vpdesai21** [comment] 2015-11-29 09:28
Same issue .. Kindly inform if there is any solution to this ..

**Comment by nodeit** [comment] 2015-11-30 15:17
+1 any updates on a fix to this?

Any good alternatives to robomongo in the meantime?

**Comment by MaDeRkAn** [comment] 2015-11-30 15:17
I tried on mongovue 1.6.9 it's same.

**Comment by andersonpimentel** [comment] 2015-11-30 15:38
@nodeit I'm using [MongoChef](http://3t.io/mongochef/)

**Comment by nodeit** [comment] 2015-11-30 15:42
@andersonpimentel thanks, I just found that one myself. It's working perfect for me.

**Comment by wowkin2** [comment] 2015-11-30 17:02
Recently, MongoLab migrated all instances to 3.0 version.
And the last Robomongo can't work with it. Waiting for updates (see https://github.com/paralect/robomongo/issues/520).

**Comment by thisismygithub** [comment] 2015-11-30 17:05
@wowkin2  
MongoChef  is worked !!
@andersonpimentel thanks!!

**Comment by wowkin2** [comment] 2015-11-30 18:08
@andersonpimentel, @thisismygithub, but MongoChef takes 10 times more RAM than RoboMongo and is slower because of Java

**Comment by nodeit** [comment] 2015-12-01 13:42
@wowkin2 valid points but the most important thing here is that MongoChef actually works with MongoLab right now whereas RoboMongo does not. 

I'm making the switch until RoboMongo gets updated then I'll reevaluate.

**Comment by bitomule** [comment] 2015-12-11 15:19
Same issue here. Mongolab sandbox + mongo 3

**Comment by digbyk** [comment] 2015-12-12 09:21
Same issue too.

**Comment by douwevdijk** [comment] 2015-12-14 13:18
Same problem. Just cannot connect.

**Comment by mariorodriguespt** [comment] 2015-12-15 05:25
+1

**Comment by rgreuel** [comment] 2015-12-27 19:21
+1

**Comment by bbatliner** [comment] 2016-01-04 01:02
Hi all, it seems like Robomongo is actually fundraising to stay alive for the next year. If you like the tool consider supporting its development! See their indiegogo campaign here: https://www.indiegogo.com/projects/save-robomongo#/.

**Comment by dur41d** [comment] 2016-01-08 02:46
+1

**Comment by wcurtis** [comment] 2016-01-09 17:17
+1

**Comment by miqueiaspenha** [comment] 2016-01-12 23:27
+1

**Comment by skotturi** [comment] 2016-01-20 04:32
+1

**Comment by welll** [comment] 2016-01-24 12:41
+1

**Comment by anorsich** [comment] 2016-01-25 06:53
@welll Actually there is [0.9 RC1 version](http://blog.robomongo.org/robomongo-rc1-for-mac-os-x/) for linux & osx  which do support mongodb 3+ and therefore supports connections to mongolab.

**Comment by schetnikovich** [comment] 2016-01-27 17:10
[Robomongo 0.9.0 RC2](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/) supports MongoDB 3.x and WiredTiger engine. For any found issues, please create new ticket.

**Closed by schetnikovich** 2016-01-27 17:10 UTC

**Comment by fpoirier1** [comment] 2016-03-16 18:05
Still doesn't work.

**Comment by JohanTh** [comment] 2016-04-02 20:04
installing 0.9.0 RC7 solved it for me

**Comment by fega** [comment] 2016-04-03 17:00
yeah, working in the last version.

**Comment by xtsimpouris** [comment] 2016-04-14 07:02
Just installed 0.9.0-RC7 but I get Authorization failed. Is there something spesific I have to do in order to achieve connection? I put connection address/port and authentication username/password but I can't get it done (tried both auth mechanisms). Thanks.

**Comment by myaskevich** [comment] 2016-04-14 07:06
Hi @xtsimpouris 
What is it telling you?
Can you also check if your DB server address/port is accessible outside robomongo?

**Comment by myaskevich** [comment] 2016-04-14 07:07
@xtsimpouris Which os are you using?

**Comment by xtsimpouris** [comment] 2016-04-14 07:09
My bad - sorry to bother you. I had to put also admin table in order to work. Thanks however :)

**Comment by banerjeesaikat6** [comment] 2016-08-01 11:25
Any change in this? I am not even able to reach to the mlab server address.

**Comment by juliashibalko** [comment] 2016-08-03 09:37
Hi @banerjeesaikat6, could you please share error message occurring on connection, robomongo version and OS version? As I checked my mLab connection and it works well for me (using 0.9.0 - RC9 version on Win10). Have attached screens with connection details below. Thank you!

![1](https://cloud.githubusercontent.com/assets/16773195/17361001/d9841dcc-5976-11e6-9f94-b3d88cf763fc.png)

![2](https://cloud.githubusercontent.com/assets/16773195/17361002/d9907ebe-5976-11e6-90c8-59c3f12d3ad2.png)

**Comment by banerjeesaikat6** [comment] 2016-08-03 16:34
It is working for me in RC6 but not in RC9 although I am doing everything
similar.

Thanks,
Saikat

**Comment by juliashibalko** [comment] 2016-08-23 18:29
@banerjeesaikat6 I have moved your problem to ticket #1166 as this card is closed, so please click the link and feel free to add any details. Thanks in advance!

**Comment by hiralkahar** [comment] 2016-09-14 04:49
Thanks. Helpful solution

**Comment by reggieboyYEAH** [comment] 2016-09-14 08:12
Same issue here 
![screenshot from 2016-09-14 16-07-22](https://cloud.githubusercontent.com/assets/7448059/18504625/ddef2650-7a95-11e6-9fbe-7b497819b349.png)

i'm using 0.9.0-RC9 to Sandbox 

My OS is ubuntu

:(

**Comment by simsekgokhan** [comment] 2016-09-15 07:52
Hi @reggieboyYEAH, I have just done a test with RC9 on Ubuntu, the connection to Sandbox was successful. Your error is high probably related to the first tab "Connection". 

Can you share screenshot from "Connection" tab please?
Also please make sure ds011725.mlab.com is reachable from your local. `ping ds011725.mlab.com`

**Comment by simonmilz** [comment] 2016-09-16 12:10
I have just done a test with RC9 on Windows x64, the connection to Sandbox was successful.

**Comment by abhinav-atmosfi** [comment] 2016-10-16 21:25
i was able to connect using the latest version as well. I tried multiple time and authorization was failing.. only to find i was using mlab credentials and not the actual database credentials. I had to create user for database in mlab and credentials i created for it worked just fine.

**Comment by juliashibalko** [comment] 2016-10-17 10:32
@abhinav-atmosfi thank you for sharing! Hope this information will help with problem solving.

**Comment by claudiuconstantin** [comment] 2016-10-22 11:37
Robomongo 0.9.0-RC10 worked for me with mLab (mongod version: 3.2.10 (MMAPv1)). Make sure that:
- in the Authentication tab you enter the correct database name;
- username is above specified database username, not mLab username;
- AuthMechanism is SCRAM-SHA-1, not MONGODB-CR;

Hope this helps!

**Comment by markmbirira** [comment] 2017-02-10 16:17
@juliashibalko's solution worked for me, Ubuntu 16.04 , Robomongo 0.9.0

**Comment by sanmak** [comment] 2017-02-18 19:52
Thanks @juliashibalko, your's solution worked.

**Comment by aboobakkar** [comment] 2017-05-26 10:31
@claudiuconstantin

**Comment by aboobakkar** [comment] 2017-05-26 10:32
@claudiuconstantin  How to get database username?. i configure only mlab username and passwords!!
