### ISSUE TITLE
reload shortcut does not work

### ISSUE THREAD

**Issue by wallaceturner** [paralect/robomongo#745] opened 2015-01-29 01:39 UTC
I'm using robomongo 0.8.4

After typing a command in the shell window and hitting Ctrl-R the command is not executed. Am forced always to right click the window with the mouse and select 'Reload'

**Comment by malyavkin** [comment] 2015-01-29 09:05
@wallaceturner Does Ctrl+Enter work? It works for me

**Comment by wallaceturner** [comment] 2015-01-29 09:42
yes Ctrl-Enter works. (thank you!) - i'm on windows 8.1. ctrl-r definitely busted for me, have tried it in all contexts, in the shell window, outside, etc

**Comment by stennie** [comment] 2015-03-10 03:42
FYI, this has been fixed in 0.8.5 (dupe of #551). Windows release coming soon :)

**Closed by stennie** 2015-03-10 03:42 UTC
Labels: duplicate
