### ISSUE TITLE
Connection via SSH Tunnel on OS X 10.11.1 El Capitan not working

### ISSUE THREAD

**Issue by jkrenge** [paralect/robomongo#964] opened 2015-10-28 14:08 UTC
I have a connection to a remote MongoDB configured, which used to work on Max OS X 10, but after the upgrade to El Capitan it's no longer working.

This is the same behaviour as I had with Sequel Pro, where an update solved the issue.

**Comment by anorsich** [comment] 2016-02-03 09:12
@jkrenge Thank you for submitting this issue. We had to disable ssh/ssl support in latest [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/) release. We are working to return it back soon. I am closing this ticket as duplicate of #1002. You can use it to keep tracking implementation progress.

**Closed by anorsich** 2016-02-03 09:12 UTC
