### ISSUE TITLE
Problem with correctly displaying Japanese in 0.8.4 (Yosemite)

### ISSUE THREAD

**Issue by mpenkov** [paralect/robomongo#735] opened 2015-01-11 07:41 UTC
I've recently upgraded to Yosemite and noticed that Japanese text is no longer being displayed correctly. Instead of Kanji, I see boxes. I'm sure that the underlying data is correct (it contains Kanji, not boxes). Furthermore, if I copy-paste the problem document into any other application, such as here, the characters display correctly:

    {
        "_id" : 1848681,
        "admin1id" : "JP.45",
        "name" : "Yamaguchi-ken",
        "asciiname" : "Yamaguchi-ken",
        "countryCode" : "JP",
        "names" : {
            "EN" : [ 
                "yamaguchi-ken", 
                "yamaguchi"
            ],
            "JA" : [ 
                "山口県", 
                "やまぐちけん"
            ]
        }
    }

What can I do to make Robomongo display Japanese text correctly again?

**Comment by mpenkov** [comment] 2015-01-11 07:45
Here's a screenshot of the "Edit document" window for the above document: 

![screenshot](http://imgur.com/r8htxp6.png)

**Comment by calfzhou** [comment] 2015-01-12 06:02
+1, the similar problem for Chinese characters.

**Comment by nonocast** [comment] 2015-01-20 16:21
+1

**Comment by dingyaguang117** [comment] 2015-01-24 07:46
+1

**Comment by XadillaX** [comment] 2015-01-24 15:14
+1 for Chinese characters.

**Comment by jacksonpan** [comment] 2015-01-25 01:58
we can build make the app by ourself then fix it. you can see the wiki, how to build

**Comment by Samurais** [comment] 2015-01-25 07:04
+1, will try to build it.

**Comment by jacksonpan** [comment] 2015-01-25 08:08
but only build debug, if build release, it has errors.
i can't fix it. and can't find it.
will you try?
would author help us?

**Comment by stennie** [comment] 2015-01-25 08:20
FYI, the character display issue is definitely fixed when built with latest Qt (dupe of #678). I haven't had free time to properly test releases but can post an 0.8.5 which appears to "work for me".

**Comment by stennie** [comment] 2015-03-10 00:09
Can you please try the OS X 0.8.5 release: https://www.dropbox.com/s/8lawkd1ka7sgia9/Robomongo-0.8.5-x86_64.dmg?dl=0

If you test this out and find any problems, please start a new issue. Thanks!

**Closed by stennie** 2015-03-10 00:09 UTC
Labels: duplicate
