### ISSUE TITLE
Authorization Failed (Mongolab Connection)

### ISSUE THREAD

**Issue by msutyak** [paralect/robomongo#1032] opened 2016-02-20 01:43 UTC
I am using the Sandbox free AWS instance from Mongolab.  I am sure I am typing in the correct credentials (db username and db password), because I am able to connect to the DB through the shell.  

However, when running this in Robomongo, I am running into the error "Authorization Failed", but it connects to the host:port.  I am using Robomongo 0.9.0-RC4.  

Mongolab is showing version: mongod version: 3.0.9

No idea why this is persisting.

**Comment by anorsich** [comment] 2016-02-20 19:56
@msutyak What authentication schema do you use (scram-sha-1 or mongo-cr)?

**Comment by anorsich** [comment] 2016-03-26 05:35
@msutyak We were not able to reproduce this issue, I going to close this ticket now. If you can provide more details or confirm that it still does not working - let's re-open.

**Comment by raam86** [comment] 2016-11-23 11:49
I have the same issue. trying to connect using shell works but with robomongo I keep getting authentication failed.

**Comment by simsekgokhan** [comment] 2016-11-26 10:59
Hi @raam86 , thanks a lot for reporting the problem.
Can you please provide more details, your Robomongo and OS version?
And connection settings details, screenshot if possible so that we can reproduce and investigate.

**Comment by simsekgokhan** [comment] 2016-11-26 11:01
Details of your remote server is also required (AWS, mongolab etc..).

**Comment by raam86** [comment] 2016-11-29 10:41
osx 10.11.6 robomongo 0.9 mongo instances are linode hosted,  mongo cloud manager managed

**Comment by simsekgokhan** [comment] 2016-12-03 09:25
@raam86 
Thanks for details. We will try to reproduce and investigate.
And in order to reproduce your problem, we need to replica your environment. As I understand you do not use mongolab, you use mongodb instances on linode virtual servers? If it is correct, we will move this into a new ticket to keep tracking easier.

**Comment by juliashibalko** [comment] 2016-12-13 15:01
Hi @raam86!
I have created a new ticket for your issue in gitHub https://github.com/paralect/robomongo/issues/1261. So please check it.
Closing this ticket.

**Closed by juliashibalko** 2016-12-13 15:01 UTC
Labels: critical, needs repro
