### ISSUE TITLE
Robomongo shows no collections when there are some.

### ISSUE THREAD

**Issue by qstyler** [paralect/robomongo#938] opened 2015-09-09 09:09 UTC
So there are actually one collection (except for system.indexes) but nothing's shown in the left explorer panel.

![image](https://cloud.githubusercontent.com/assets/5556580/9757814/1e8ca5e8-56e3-11e5-9d2d-fd9bb22eea8c.png)

**Comment by SadBunny** [comment] 2015-09-09 09:12
Your screenshot hows that you're on database "komparu_product_dev" with that query, while you're looking at "komparu_product_test" in the treeview (left panel). Your "komparu_product_dev" does show collection "product" in the left panel.

**Comment by underkin** [comment] 2015-09-09 15:15
Something similar happens to me. I think I'm on the right node in the tree:
![screenshot 2015-09-09 05 14 19](https://cloud.githubusercontent.com/assets/1251069/9765804/504138fa-5716-11e5-90f1-01eb86a480a5.png)

**Comment by qstyler** [comment] 2015-09-09 15:24
Sorry, took screenshot from wrong server.
Here's the actual one.
![image](https://cloud.githubusercontent.com/assets/5556580/9766130/a94aa3cc-5717-11e5-85d7-f340406ad53b.png)

**Comment by underkin** [comment] 2015-09-10 09:40
I Updated mongo version to latest one and it works fine now!

Hope this helps .

regards



On 9 Sep 2015 at 17:24:59, Kosta Bodnia (notifications@github.com) wrote:

Sorry, took screenshot from wrong server.
Here's the actual one.

**Comment by Joris-van-der-Wel** [comment] 2015-09-29 16:10
#940 is a duplicate of this one

Anyway, I am having the same issue:

Robomongo 0.8.5 on OS X
mongod v3.0.6 on a centos 7.1 server (repo: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/3.0/x86_64/) , direct connection without authentication, without ssl. Disabling iptables and selinux has no effect.

Strangely, if I run mongod v3.0.6 (installed using brew) on localhost, there is no issue.

**Comment by YaTaras** [comment] 2015-12-13 01:05
I had the same problem with Robomongo 0.8.4 / 0.8.5 versions and mongod v.3.2.0 on Ubuntu 14.04. I reinstalled mongo to the previous version (v3.0.7) and now it works well.

**Comment by PeterMurdoch** [comment] 2015-12-18 23:02
bump same issue

**Comment by michelbl** [comment] 2015-12-20 16:32
Same issue with robomongo 0.8.5 and mongodb 3.2.0 on ubuntu 14.04.

**Comment by tarikmlaco** [comment] 2015-12-20 23:23
same issue on osx. robomongo 0.8.5, mongodb 3.2.0. this issue has been on since september...any chance of a fix?

**Comment by hoeni** [comment] 2015-12-28 13:15
Same issue here, Win 10, RoboMongo 0.8.5, MongoDB 3.2.0.
Reinstalled MongoDB 3.0,8 and everything works fine again, so RoboDB seems to have an issue with MongoDB 3.2...

**Comment by megglos** [comment] 2015-12-28 18:02
+1 mongo 3.2.0 & RoboMongo 0.8.5

**Comment by JTrotta** [comment] 2015-12-29 12:10
In fact it has. Please read the here http://blog.robomongo.org/robomongo-future/.

**Comment by schetnikovich** [comment] 2016-01-27 17:38
Starting from [Robomongo 0.9.0](http://blog.robomongo.org/robomongo-rc2-for-windows-mac-os-x-and-linux/), we support MongoDB 3.x, including WiredTiger engine. Let us know, how it works for you. For any found issues, please create new ticket.

**Closed by schetnikovich** 2016-01-27 17:38 UTC

**Comment by deehidayat** [comment] 2016-03-11 07:23
well thanks a lot Robomongo 0.9.0 works for me.

**Comment by nickgermaine** [comment] 2016-03-12 14:22
This fixed the issue for me.
Mongod 3.2.3, Robomongo 0.9.0 RC4

**Comment by janpauldahlke** [comment] 2017-05-30 10:26
came across the same issue today. the solution is downgrade from 1.0.0 to 0.9.0? even installing robomongo again didnt fixed it. my mongo --version is 

> db version v3.4.3
and robomongo is
v1.0.0.
working on mac osX 10.11.6

best regards

**Comment by juliashibalko** [comment] 2017-05-30 16:48
Hi @janpauldahlke, thanks for reporting! Robomongo will support mongoDB 3.4 only in next 1.1 release. But we offered a beta version of 1.1 - see https://github.com/Studio3T/robomongo/issues/1250#issuecomment-301036770. So if possible, please check this build. I hope it will solve your issue.

**Comment by AntonyIS** [comment] 2019-10-05 21:41
Had the same issue. Temporary solution is to restart robomongo
