### ISSUE TITLE
Aggregation option { explain: true } doesn't  bring information about pipeline execution

### ISSUE THREAD

**Issue by wagnerjs** [paralect/robomongo#773] opened 2015-03-05 14:20 UTC
When i run:

``` db.collection.aggregation( [ ...my pipeline...], { explain: true } ) ```

result is the same of

``` db.collection.aggregation( [ ...my pipeline...] ) ```

Mongo shell shown the correct result. 

Regards

**Comment by stennie** [comment] 2015-03-05 14:32
@wagnerjs Duplicate of #495. There's an example there of alternate `runCommand()` syntax that will work for passing options to aggregation until #520 is resolved.

Thanks!

**Comment by wagnerjs** [comment] 2015-03-05 14:42
I did not find this issue in my search.
Thanks for your time!

Regards

**Comment by anorsich** [comment] 2016-01-30 07:51
@wagnerjs  Latest [0.9.0](http://blog.robomongo.org/robomongo-0-9-0-rc3-released/) is based on Mongodb shell 3.2 and support aggregate arguments. Let us know if it worked for you.

**Closed by anorsich** 2016-01-30 07:51 UTC
Labels: duplicate
