### ISSUE TITLE
Value of type "Double" are read as "Int32"

### ISSUE THREAD

**Issue by pietro909** [paralect/robomongo#834] opened 2015-04-02 14:40 UTC
Hi there,
thank you for RoboMongo as it made my work easier.

By the way, I'm getting this strange behaviour: when I click "Edit document" the value of type **Double** are rendered as **Int32** so even if I modify another value they are saved back to the DB with the new type... and this is breaking my DB reader :-)
I need to re-edit them and manually set the value as float (just adding *.0), and this way it works.

![mongoerror](https://cloud.githubusercontent.com/assets/2094604/6966026/2c7103b2-d956-11e4-97e9-dab461cc0eea.jpg)

Have you got any clue about this?

Thank you,
Pietro

**Comment by stennie** [comment] 2015-04-02 18:20
@pietro909 Can you confirm what version of Robomongo you are using? This sounds like a duplicate of #622 which should be fixed in Robomongo 0.8.5.

Thanks!

**Closed** 2015-04-03 16:24 UTC

**Comment by pietro909** [comment] 2015-04-03 16:27
Hi @stennie thank you for your prompt reply: I don't know the version we're using and I will be out of the office till Wednesday.
I strongly believe that this is a duplicate, so I'm going to close it.
Sorry for the double issue, I wish you a happy Easter!

**Comment by stennie** [comment] 2015-04-03 23:18
@pietro909 Thanks for the update. Please do reopen with more details if this is still a problem for you in Robomongo 0.8.5.

Enjoy your Easter break!
