### ISSUE TITLE
Robomongo not connecting to Enterprise edition

### ISSUE THREAD

**Issue by divman23** [paralect/robomongo#835] opened 2015-04-03 14:01 UTC
We were using Robomongo till our Admin team enables mongo authentication. But after enabling, I tried to connect mongodb with URI details, but it is not connecting. It says authentication failed. Could anyone help here on how to connect with below URI format.

"mongodb://(user):(pass)@(host):(port)/?authMechanism=PLAIN&authSource=$external"

**Comment by stennie** [comment] 2015-04-04 21:14
@divman23 Thanks for the report. This is a duplicate of #718: Robomongo 0.8.x does not support authentication with `$external` authSources yet. This is planned to be addressed in the 0.9.0 milestone along with support for MongoDB 3.0.

**Closed by stennie** 2015-04-04 21:14 UTC
Labels: duplicate

**Comment by rkazanova** [comment] 2016-04-01 09:53
is it available in 0.9.0 RC7?

**Comment by anorsich** [comment] 2016-04-01 13:38
Hi @rkazanova. Unfortunately, Robomongo still does not support `$external` authSource. But a good news that we do plan work on that feature. Let's use #718 to keep track implementation progress.
