### ISSUE TITLE
Multi tab not multithreaded ?

### ISSUE THREAD

**Issue by Owumaro** [paralect/robomongo#754] opened 2015-02-09 10:31 UTC
Hi,

I'm using Robomongo 0.8.4 on Ubuntu 14.04.
Today while I was executing a big query in one tab, I tried to close another tab while the query was still in progress. Robomongo became idle until the query ended (minutes later) and then closed the other tab.

This is not very user friendly as we're not sure of what's happening, if the query is still processing or if Robomongo crashed for some reason. And we should be able to write another query while the first one is in progress.

Thanks,

**Comment by stennie** [comment] 2015-02-19 22:19
@Owumaro Thanks for reporting .. this is a duplicate of #661.

**Closed by stennie** 2015-02-19 22:19 UTC
