### ISSUE TITLE
Crash on connecting Ext display (MAC)

### ISSUE THREAD

**Issue by sergio-doman** [paralect/robomongo#966] opened 2015-10-30 10:09 UTC
Hi, 

when I'm trying to connect/disconnect external display application crashes each time and I need to restart it.
OS X 10.9.5 (13F1134)

**Comment by spoonscen** [comment] 2015-11-04 21:20
Same here.  Experiencing the same issue OSX 10.11 (15A284)

**Comment by will-weiss** [comment] 2015-11-04 21:21
I too experience this issue daily - I'm running OSX Yosemite 10.10.5

**Comment by gavruk** [comment] 2016-01-29 17:22
@sergio-doman @spoonscen @will-weiss I cannot reproduce this with Robomongo 0.9.0 RC3 on OS X 10.11.3
Can you still reproduce this with 0.9.0?

**Comment by anorsich** [comment] 2016-02-03 09:15
@will-weiss @spoonscen I do beleive this issue has been fixed with latest [0.9.0 RC4](http://blog.robomongo.org/robomongo-rc4/). I am closing this issue for now, if you still have issues, please reopen this issue.

**Closed by anorsich** 2016-02-03 09:15 UTC
