### ISSUE TITLE
don't reset column's width after refresh

### ISSUE THREAD

**Issue by olshevskiy87** [paralect/robomongo#1078] opened 2016-04-15 10:19 UTC
hello.

when I execute a query in the tab, results columns width is reset to the default value. it's really annoying thing.

is there any config option to disable this action? or maybe it should be implemented in future.

**Comment by myaskevich** [comment] 2016-04-15 10:28
Hi Dmitriy.

Thanks for your report! This is indeed quite annoying.

I'm afraid there is no such option to hotfix it at the moment. But, this doesn't sound like a lot of work, so good news -- you may expect this issue to get fixed in one of the upcoming releases soon.

We'll keep you posted.

**Comment by olshevskiy87** [comment] 2016-04-15 19:02
@myaskevich cool! i'll be waiting. thanks in advance :)

**Comment by anorsich** [comment] 2016-04-15 20:58
It sounds like it's a duplicate of #333. Let's use that ticket to track a progress.

**Closed by anorsich** 2016-04-15 20:58 UTC
Labels: cosmetic
